# Generated by Django 2.2.24 on 2021-07-16 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(default='Apellidos', max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('fecha', models.DateField(auto_now=True)),
                ('objetivo', models.IntegerField()),
                ('porcentaje_comision', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tipo de crédito', max_length=50)),
                ('costo', models.IntegerField()),
                ('tasa_interes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Tipo de tarjeta', max_length=50)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sucursal', max_length=50)),
                ('calle_y_numero', models.CharField(default='Calle y No', max_length=50)),
                ('colonia', models.CharField(default='Colonia', max_length=50)),
                ('region', models.CharField(default='Region', max_length=50)),
                ('estado', models.ForeignKey(default='Estado', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
                ('municipio', models.ForeignKey(default='Municipio', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Municipio')),
                ('pais', models.ForeignKey(default='País', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='estado',
            name='idPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais'),
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto_colocado', models.IntegerField()),
                ('comision_ganada', models.IntegerField()),
                ('promotor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Promotor')),
            ],
        ),
    ]
