# Generated by Django 2.2.24 on 2021-07-23 18:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('calle_y_numero', models.CharField(max_length=50)),
                ('colonia', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('cantidad_hijos', models.IntegerField()),
                ('rfc', models.CharField(max_length=13)),
                ('idEstado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado')),
                ('idMunicipio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Municipio')),
                ('idPais', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=datetime.date.today)),
                ('monto_otorgado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dia_pago', models.PositiveSmallIntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='StatusCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSolicitudCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.RenameField(
            model_name='comision',
            old_name='promotor',
            new_name='idPromotor',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='solicitudcredito',
            name='tasa_interes',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='tipotarjeta',
            name='costo',
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='fecha_solicitud',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='monto_solicitado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='idEstado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='idMunicipio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Municipio'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='idPais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais'),
        ),
        migrations.AddField(
            model_name='tipotarjeta',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=2),
        ),
        migrations.AlterField(
            model_name='comision',
            name='comision_ganada',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='comision',
            name='monto_colocado',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='apellidos',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='calle_y_numero',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='colonia',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tipotarjeta',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(default=datetime.date.today)),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('idCredito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Credito')),
            ],
        ),
        migrations.AddField(
            model_name='credito',
            name='idSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.SolicitudCredito'),
        ),
        migrations.AddField(
            model_name='credito',
            name='idStatusCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusCredito'),
        ),
        migrations.AddField(
            model_name='credito',
            name='idTipoCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoCredito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idPromotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Promotor'),
        ),
        migrations.CreateModel(
            name='AyudaCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField()),
                ('fecha_aprobacion', models.DateField(null=True)),
                ('apoyo_aprobado', models.PositiveIntegerField()),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente')),
            ],
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='idStatusSolicitudCredito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusSolicitudCredito'),
        ),
        migrations.AddField(
            model_name='solicitudcredito',
            name='idTipoCredito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoCredito'),
        ),
    ]
