# Generated by Django 2.2.24 on 2021-07-27 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210723_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPromotor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='promotor',
            name='status',
        ),
        migrations.AddField(
            model_name='promotor',
            name='idSucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Sucursal'),
        ),
        migrations.AddField(
            model_name='promotor',
            name='idStatusPromotor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusPromotor'),
        ),
    ]
