# Generated by Django 2.2.24 on 2021-07-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210727_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotor',
            name='idStatusPromotor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusPromotor', verbose_name='Estatus'),
        ),
    ]
