# Generated by Django 2.2.24 on 2021-07-27 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210727_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudacovid',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idMunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='idPromotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Promotor', verbose_name='Promotor'),
        ),
        migrations.AlterField(
            model_name='comision',
            name='idPromotor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Promotor', verbose_name='Promotor'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='idSolicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.SolicitudCredito', verbose_name='Solicitud'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='idStatusCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusCredito', verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='credito',
            name='idTipoCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoCredito', verbose_name='Tipo credito'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='idPais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='idEstado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='idCredito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Credito', verbose_name='Credito'),
        ),
        migrations.AlterField(
            model_name='promotor',
            name='idSucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='idStatusSolicitudCredito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusSolicitudCredito', verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='solicitudcredito',
            name='idTipoCredito',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoCredito', verbose_name='Tipo de credito'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='idEstado',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='idMunicipio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Municipio', verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='idPais',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Pais', verbose_name='Pais'),
        ),
    ]
