# Generated by Django 2.2.24 on 2021-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210727_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Registro Activo'),
        ),
    ]
