# Generated by Django 2.2.24 on 2021-08-06 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_pais_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcredito',
            name='idCliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credito',
            name='idCliente',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='tipotarjeta',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
    ]
