# Generated by Django 2.2.24 on 2021-08-06 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210805_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_tarjeta', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('limite_credito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idCredito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Credito', verbose_name='Credito')),
                ('idTipoTarjeta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TipoTarjeta', verbose_name='Tipo Tarjeta')),
            ],
        ),
    ]
