# Generated by Django 2.2.24 on 2021-08-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210805_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotor',
            name='fecha',
        ),
    ]
