# Generated by Django 2.2.24 on 2021-08-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_promotor_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotor',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
