# Generated by Django 2.2.24 on 2021-08-06 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210806_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcredito',
            name='idStatusSolicitudCredito',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.StatusSolicitudCredito', verbose_name='Estatus'),
        ),
    ]
