# Generated by Django 2.2.24 on 2021-08-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210806_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ayudacovid',
            name='motivo',
        ),
        migrations.AlterField(
            model_name='ayudacovid',
            name='apoyo_aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
