# Generated by Django 2.2.24 on 2021-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210806_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='monto_transacciones',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tarjetacredito',
            name='num_transacciones',
            field=models.IntegerField(null=True),
        ),
    ]
