from django.contrib import admin
from .models import Pais, Estado, Municipio, Sucursal, TipoTarjeta, SolicitudCredito, Promotor, Comision, TipoCredito, StatusSolicitudCredito, Cliente, StatusCredito, Credito, Pagos, AyudaCovid

admin.site.register(Pais)
admin.site.register(Estado)
admin.site.register(Municipio)
admin.site.register(Sucursal)
admin.site.register(TipoTarjeta)
admin.site.register(SolicitudCredito)
admin.site.register(Promotor)
admin.site.register(Comision)
admin.site.register(TipoCredito)
admin.site.register(StatusSolicitudCredito)
admin.site.register(Cliente)
admin.site.register(StatusCredito)
admin.site.register(Credito)
admin.site.register(Pagos)
admin.site.register(AyudaCovid)
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
#admin.site.register()
